examples/basic.rs, examples/set_env.rs, examples/syscalls.rs, src/cmd.rs, src/ptracer.rs
- Allow setting tracee environment in `Command`
- Exec with `execve()`
- Breaking change: `spawn()` now accepts a `Command` instead of an arg vector
Closes #4.
=> Enable setting `Command` environment

src/ptracer.rs
This mirrors the implementation in normal fork and clone, and seems to prevent a
panic around line 421 of ptracer.rs.
Fixes #7
=> Have the vfork handler register its new child with the ptracer

CHANGELOG.md, src/error.rs, src/lib.rs, src/ptracer.rs
- Revisit `Error` enum
- Use `Error::Internal` for logic errors, unreachable code
- Remove all panics in `ptracer`
Closes #5.
=> Revisit errors, remove all panics

CHANGELOG.md, src/error.rs, src/ptracer.rs
- Add a `String` context to `Error::Internal`
- Remove an over-zealous bail in the `seccomp` event-stop handler
=> Add context to `Error::Internal`, fix seccomp event bug

CHANGELOG.md, Cargo.toml
**Note:** this update raises our minimum supported `rustc` to 1.41.0.
=> Update `nix` to 0.21

.github/workflows/ci.yml, Cargo.toml, examples/syscalls.rs, script/parse_perf_trace.py, script/syscall-tracepoint-test
- Update the `syscalls` example with tracee-quieting and TSV output options (to support testing)
- Add scripts for testing syscall tracing by comparing against kernel tracepoint events
- Run integration test in CI task
=> Add syscall tracepoint test

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/error.rs, src/ptracer.rs, tests/tracee_died.rs
Tracees can die while stopped, but the `ptrace()`-level error is ambiguous without context. The tracer has the required context, so we now detect stopped tracee death (when unambiguous), and surface it to users.
- Add variant `Error::TraceeDied`, which is only emitted when a `ptrace()` call fails on a tracee known to be in ptrace-stop
- Add the method `Error::tracee_died()`, which returns `true` if the `Error` variant is `Restart` or `TraceeDied`
- Use a private extension trait to map internal `ptrace()` errors to `Error::TraceeDied`, when appropriate
- Run tests in CI
Closes #39.
=> Add user-facing detection of stopped tracee death

CHANGELOG.md, examples/syscalls.rs, src/ptracer.rs
Almost all `Stop` variants have a `Pid`-valued field that identifies the stopped tracee. This is redundant when accessed via the `Tracee`, which we typically expect any `Stop` consumer to have access to. This is also confusing, since we use tuple structs, and there are sometimes multiple PIDs associated with a stop.
Remove the redundant PIDs. Require users to pass either the `Tracee` or tracee PID when needed.
This is a breaking change.
=> Remove redundant `Stop` fields

CHANGELOG.md, src/ptracer.rs
We removed contextually-redundant PID fields in #50, which reduced within-`Stop` ambiguity in the meaning of variant fields. But the field semantics are still not obvious from type alone. For example, a PID from a `Stop::Fork` is the PID of the newly-forked process, but the PID from a `Stop::Exec` is the old PID of the replaced task. Just use named fields whenever we have a ptrace-stop with data.
Closes #41.
=> Use named fields for `Stop` variants with data

.github/workflows/ci.yml, CHANGELOG.md, src/lib.rs, src/ptracer.rs, tests/tracee_died.rs
- Condition `Register`-related definitions on `target_arch`
- Add CI task to run a cross-compiled `check` for `aarch64-unknown-linux-gnu`
Closes #52.
=> Conditionally compile arch-specific features

examples/hw_break.rs, examples/syscalls.rs, src/ptracer.rs
=> Remove redundant suffix from `Stop` variants

test-programs/nop/Makefile
We defined `CFLAGS`, but didn't use it. The tests don't require change, because (1) our flags just enforce the default behavior, (2) in the relevant test, we double-check that the test binary is non-PIE.
=> Set `CFLAGS` when building test program

CHANGELOG.md
Our changelog update in #57 didn't actually finalize the release entry and start a new "Unreleased" section.
Closes #59.
=> Fix v0.6.0 changelog entry

src/ptracer.rs
This PR adds support for getting and setting the general-purpose registers on aarch64-linux-android.
=> Add support for getting/setting registers on aarch64-linux

Cargo.toml, src/aarch64.rs, src/ptracer.rs
Depend on a newer `libc`, which now provides `PTRACE_GETREGSET` and `PTRACE_SETREGSET` for `android`.
=> Update `libc` dependency

Cargo.toml, src/error.rs, src/ptracer.rs
`nix::Error` is now just an alias for `Errno`.
=> Update `nix` dependency

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md
This addresses two issues:
- Broken builds with Rust versions we claim to support (via [`serde`](https://github.com/serde-rs/serde/issues/2255))
- Upcoming [MSRV conflict](https://github.com/nix-rust/nix/pull/1792) in `nix` (h/t @Porges)
=> Update MSRV to 1.56.1

CHANGELOG.md, src/error.rs
We intended `internal_error!()` to expand to a block expression enclosing an early return. It _actually_ expands to `return Err(..)`, as an expression. All of our use sites work as-is, but the non-block version will eventually become a [hard error](https://github.com/rust-lang/rust/issues/79813) due to our use of a semicolon. Fix the offending macro body.
=> Expand to block expression in error macro

.github/workflows/ci.yml, script/hw-breakpoint-test, test-programs/nop/Makefile
Update the clang version expected in integration tests. The runner images we're using no longer ship `clang-11.` Also update the Makefile for the test program to override new runner defaults re PIE compilation.
=> Fix integration tests

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md
A transitive dependency of `ntest` has an MSRV of 1.64, which breaks the current test build. That's only a few months newer than our current MSRV, so adopt that.
=> Update MSRV to 1.64

CHANGELOG.md, src/ptracer.rs
Enable reading and modifying the default `Options` applied to newly-spawned tracees.
Closes #96.
=> Add default options accessors

CHANGELOG.md, src/ptracer.rs
Support the use case in #88, and others, but stop short of trying to parse a `NUL`-terminated C string.
=> Add method to open tracee memory as `File`

CHANGELOG.md, src/ptracer.rs, tests/tracee_died.rs, tests/wait_untraced_child.rs
- Only poll known tracee PIDs with `wait(2)` to avoid breaking `std::process::Child::wait()`
- Poll tracees with `WNOHANG`, apply cool-off poll delay if no new statuses
- Add accessors to allow tuning poll delay, default to 100ms
- Add test case
Closes #100.
=> Only poll known tracees with `wait(2)`

src/ptracer.rs
The original accessors were a bit quirky: they only allowed returning references to inner values that are both small and `Copy`. Instead, use the more common `property()`/`set_property()` accessor pattern, and return owned copies from the getters.
=> Improve accessor method ergonomics

src/ptracer.rs, tests/child_exit_status.rs, tests/tracee_wait_child.rs, tests/wait_untraced_child.rs
Detach from tracees upon restart when we observe `PTRACE_EVENT_EXIT`. This allows tracer-external `wait()` calls to behave as expected.
Add tests for 2 critical cases:
- Post-detach behavior of `std::process::Child::wait()`, in the same process as the tracer
- Tracee calls to `wait()` on formerly-traced, exiting grandchildren of the tracer process
Closes #119.
=> Detach from exiting tracees

Cargo.toml, tests/child_exit_status.rs, tests/support/mod.rs, tests/tracee_died.rs, tests/tracee_wait_child.rs, tests/wait_untraced_child.rs
- Add an `assert_equivalent()` test helper, which tests trace equivalence modulo PID normalization
- Implement an event trace normalizer, which converts a trace into a representative with normalized PIDs
- Update existing integration tests to check for expected event traces (in addition to existing assertions)
- Remove a vestigial polyfill that was only needed for now-unsupported `rustc` versions
=> Add event trace test assertions
